export LOCALAPPSPREFIX=$(pwd)/result
export KDEDIRS=${KDEDIRS}:${LOCALAPPSPREFIX}
export PATH=${LOCALAPPSPREFIX}/bin:$PATH
export LD_LIBRARY_PATH=${LOCALAPPSPREFIX}/lib
export XDG_DATA_DIRS=${XDG_DATA_DIRS}:${LOCALAPPSPREFIX}/share
#export CMAKE_PREFIX_PATH=${LOCALAPPSPREFIX}
#export PKG_CONFIG_PATH=${LOCALAPPSPREFIX}/lib/pkgconfig:${LOCALAPPSPREFIX}/share/pkgconfig
